### ISSUE TITLE
Bug: Overeager evaluation of entry and exit actions

### ISSUE THREAD

**Issue by sunny-mittal** [statelyai/xstate#3509] opened 2022-08-08 17:27 UTC
### Description

It seems `entry` and `exit` actions are fired repeatedly when the state is entered/exited. I stumbled upon the bug somewhat accidentally and noticed an entry action running 103 times in my project when the machine started up. Changing it to an `exit` action resolved the issue and was suitable for my use case but in other places, exit actions are also running multiple times. The number of times it runs seems to be strangely predictable in the same machine but different across machines. For example, my issue above seeing the action run 103 times happens consistently with the same number of logs and in another machine, it happens 6 times. Both are reproducible but with differing counts. I put together a small codesandbox that illustrates the issue. You'll notice the serialized action runs 4 times and the inline action runs twice.

### Expected result

Actions should only run once unless an explicit event invokes them again.

### Actual result

Actions are running multiple times in a single execution chain.

### Reproduction

https://codesandbox.io/s/little-cherry-hlnss2?file=/src/App.js

**Comment by Andarist** [comment] 2022-08-08 18:29
You are using React's `StrictMode` and thus the machine gets "restarted" because it starts in React's effect. You can read more about the changes introduced in `StrictMode` in React 18 here: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

**Comment by sunny-mittal** [comment] 2022-08-08 18:54
@Andarist I forgot about that being the default in codesandbox and it would explain the issue there, but I have a machine that runs its entry action 103 times in my work project. I can't really post sample code from that in any useable way but I can try to repro it in codesandbox without StrictMode turned on.

**Comment by sunny-mittal** [comment] 2022-08-08 19:00
The simplified machine that generates the above log is as follows. I've omitted a lot of states but those shouldn't affect this behavior as this state is a one-time state:
```
const machine = createMachine(
  {
    tsTypes: {} as import("./machine.typegen").Typegen0,
    schema: {
      context: {} as Context,
      events: {} as Event,
      services: {} as Services,
    },
    type: "parallel",
    states: {
      ui: {
        initial: "waiting",
        states: {
          waiting: {
            exit: "cache initial input",
            always: "location",
          },
          location: {
            on: {
              next: "day",
            },
          },
        },
      },
    },
  },
  {
    actions: {
      "cache initial input": assign(({ input }) => {
        console.log("in assign", Date.now())
        return { initialInput: input }
      }),
    },
  },
)
```

**Comment by Andarist** [comment] 2022-08-08 19:14
Could u prepare this in a runnable form (like a codesandbox)?

**Comment by sunny-mittal** [comment] 2022-08-08 19:50
The codesandbox I provided in the main post does exhibit the issue with StrictMode removed but it only evaluates the assign twice (which is still a problem, especially for something like telemetry or other fire-and-forget API calls). I've updated [my codesandbox](https://codesandbox.io/s/little-cherry-hlnss2?file=/src/App.js) to hopefully be a bit more revealing. It now seems to me that the issue is in actions that use the `Assigner` overload of the action creators. You can see in the logs that the `pure` action and the `assign` action are executed three times while the non-action creator is executed once. I hope this enough to see there's a genuine bug and even these minor changes caused the entry count to go from 2 to 3 so you can imagine in larger machines/components that it could grow much larger (and does).

**Comment by sunny-mittal** [comment] 2022-08-08 19:55
I think I may have identified the source of the issue...it seems to be somewhat proportional to the number of `useSelector` calls (at least in how I'm using it). I added two repeated useSelector calls that select the same value and the number of executions of the entry action has increased accordingly.

**Comment by sunny-mittal** [comment] 2022-08-08 19:56
Is it my use of `useSelector` that's incorrect? I was under the impression that I can select out whatever I want from the machine to reduce re-renders but it also seems to be the cause of this issue.

**Comment by sunny-mittal** [comment] 2022-08-08 19:57
Sorry for all the comments...but this seems to be confirmed. By removing the calls to `useSelector`, the action runs once. With each added call to `useSelector`, an additional action is fired.

**Comment by davidkpiano** [comment] 2022-08-08 20:43
>  it only evaluates the assign twice (which is still a problem, especially for something like telemetry or other fire-and-forget API calls)

Keep in mind that assign actions should be pure.

**Comment by sunny-mittal** [comment] 2022-08-08 20:50
@davidkpiano yea it occurred to me while typing that that in the case of telemetry and any fire-and-forget actions that hit APIs, they shouldn't be done inside of a pure or assign or any other action creator (and I don't abuse them that way). It still does seem to have performance implications though even if the end result is the same. For example, in my case where I had 103 `entry` actions being run, changing that to an `exit`, which in my case solved the issue, had noticeable performance improvements in the UI.

**Comment by sunny-mittal** [comment] 2022-08-08 20:56
I've definitely tracked this down to be an issue with useSelector though. Am I using them incorrectly? In theory, I could create a single selector that returns a grouping of what all my current selectors return but that doesn't feel like a "best practice" to me. Reading the xstate docs, it seems my usage of useSelector is correct and that this is unintended behavior.

**Comment by Andarist** [comment] 2022-08-09 08:44
At the moment, entry `assign` actions for the **initial state** might get re-executed multiple times like this.

The current state of a not started interpreter is read like this within `useSelector`:
https://github.com/statelyai/xstate/blob/214baebba2f88317d7081ff13598a7a59422bc72/packages/xstate-react/src/utils.ts#L23

We can't read `service.initialState` (and cache it in the service) because it might lead to creating `spawn`ed actors which can't happen before React's commit phase. I think that we could cache some kind of `service._pureInitialState` though to remedy this a little bit. Note though that this would still execute those `assign` actions at least twice - once when computing this `_pureInitialState` and the second time when actually starting the machine in an effect.

This issue is mostly already fixed in v5 where we have refactored the implementation and we can cache the true `initialState` more easily.

**Comment by davidkpiano** [comment] 2023-01-23 04:20
It seems this link is broken: https://codesandbox.io/s/little-cherry-hlnss2?file=/src/App.js 

Closing as the original issue is unrelated to XState and more related to how React strict mode works, with double-effect execution. If the problem can be reproduced and pinpointed to `useSelector`, we can reopen this issue.

**Closed by davidkpiano** 2023-01-23 04:20 UTC
Labels: bug
