### ISSUE TITLE
ActorRef<any> is wider than desirable when representing a machine

### ISSUE THREAD

**Issue by VanTanev** [statelyai/xstate#2528] opened 2021-08-18 12:20 UTC
**Description**
Currently, `ActorRefFrom<Machine>` returns an `ActorRef` object with the following `getSnapshot()` type:
```ts
interface ActorRef extends ... {
   getSnapshot: () => StateFrom<Machine> | undefioned
}
```

However, a machine actor ref will never return `undefined` from `getSnapshot()`. 

The only current solution is to sprinkle bangs when machine refs are used, eg 
```ts
ctx.childMachineRef.getSnapshot()!.matches('someState')
```

**Expected Result**
`ActorRef` instances that can be inferred at creation time to always return a defined results for `getSnapshot()` should do that.

**Discussion**

I attempted to this, but quickly ran into obscure edge cases with the ActorRef types, eg when combined with the `send()` action creator:
```ts
export type ActorRefFrom<
  T extends StateMachine<any, any, any> | Promise<any> | Behavior<any>
> = T extends StateMachine<infer TContext, any, infer TEvent, infer TTypestate>
  ? NonNullableObjectFnReturnType<ActorRef<TEvent, State<TContext, TEvent, any, TTypestate>>> & {
      /**
       * @deprecated Use `.getSnapshot()` instead.
       */
      state: State<TContext, TEvent, any, TTypestate>;
    }
  : T extends Promise<infer U>
  ? ActorRef<never, U>
  : T extends Behavior<infer TEvent1, infer TEmitted>
  ? ActorRef<TEvent1, TEmitted>
  : never;


type NonNullableObjectFnReturnType<T> = T extends object ? 
  {
    [P in keyof T]-?: NonNullableFnReturnType<T[P]>
  } : T

type NonNullableFnReturnType<T> = T extends (...args: infer Args) => infer R ? (...args: Args) => NonNullable<R> : T
```

The reason is that `NonNullableObjectFnReturnType<ActorRef<TEvent, State<TContext, TEvent, any, TTypestate>>>` actually no longer matches `ActorRef<any>`

Edit: I have solved the above incompatibility, available in #2529

**Comment by VanTanev** [comment] 2021-10-30 11:38
It doesn't seem like this is moving forward, although I really would've liked `getSnapshot()` to not return `undefined`.

**Comment by davidkpiano** [comment] 2021-10-30 22:22
It's still a valid issue, so we'll keep it open.

**Comment by davidkpiano** [comment] 2022-03-13 04:23
This no longer occurs - `.getSnapshot()` from an `ActorRef<typeof someMachine>` no longer has `undefined` as one of the types.

**Comment by Andarist** [comment] 2022-03-13 09:37
This is not quite true, the issue is still here and `ActorRef<typeof someMachine>` is something that is accidentally allowed but it shouldn't be. To convert a machine to an actor we need to use `ActorRefFrom`, see [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQMY2gJQKYDMA0K6WeAYlBCIalNgIYzYCydqAFsAHbaHKcCeAZRgNscAL5xcFEHADkADwDOIxnLgB6DXBj8w2JQC44AFgB0AZgAMZgGwAoe6gicVcEKw7c4AXjg16RhZ2LmwACgRxAEpHLR0OJThgRKVKbAB3NgY4VlRgABNsThEAGxL+HKUlYABzTjoAIxKxBuxUOgBXJTFhUWCvMWwFRk58xN7GADkIQpzR+K64AAMPEO4zXX1jACIGSmBUbbgAHzht53AIDtGj0+2wOig6MuwS27PcLmf37YSMKH42yW9jidHmMCy8GSlWqdUazR0EDgAFEAG5FGAAeQaACs2vAIdloTiuvAlkhNthjCooFwahJgYVUCVHmJnK54Kx-gBGYxof44XAAHkpEFw7k8oQAfHB7ENILB-C43Ep6mAlGwIDBub4csQoNyzDVsDBBGqNVqwjE4nBbXb7QA9AD8jiZLNoSo5ev+ACY+frBeRKCK9NgxRK1tgZSDtBCxJSkokMEiSi56akdOkIEoWRq4FnOHJ4JwDq8KvlkmAWRUlqdroVPtx8ks4GxsB6Gh14Ok2WDWxB0VA4AP2-ExEtVXR1ZqYD6Wxg4N0xMAYHKFAr4OyVeaZz7dVzoD6jSazVOLTArTH7dfbc7YtpmjA5IlnhmAI4dA4Aa3KcEHwFwCoIWhew3VZKRrnQYAXD1VBsDAU1VHCFRRD5AQJmwKJjFRCACnsXJ4MQ0QwknactR9GI1w3HRQzgABJJQAFVRjwUJ8mRYYigrTgan5aAMNPMj4D8etWKbOAhhGMYaP0cNSPPPcnR0KAOjEYxcFfbArxvO07yAA) that show cases the problem outlined in this PR and that adds some useful comments.

**Comment by davidkpiano** [comment] 2022-03-13 13:47
Sorry, I meant `ActorRefFrom<typeof someMachine>`

**Comment by Andarist** [comment] 2022-03-13 16:15
Right, I've assumed that u might have meant that and rechecked this one as well - the `| undefined` is still returned from its `getSnapshot`.

**Comment by Andarist** [comment] 2023-09-14 11:05
I believe that this is somewhat addressed by all of the type-related changes in v5. It's nowadays possible to configure actor types and have much better/accurate `snapshot.children` types.

**Closed by Andarist** 2023-09-14 11:05 UTC
Labels: typescript, core
