### ISSUE TITLE
Machines don't invoke service when spawned

### ISSUE THREAD

**Issue by wuweiweiwu** [statelyai/xstate#1161] opened 2020-04-27 23:52 UTC
**Description**

I followed the reddit example but with `createMachine` instead of `Machine` and found that the subreddit machine which should send an api call on `spawn` does not. This does not occur with `Machine`

**Expected Result**

expect `createMachine` and `Machine` to have the same behavior

**Actual Result**

subreddit machine is always in `loading` state and never invokes the service

**Reproduction**

https://codesandbox.io/s/awesome-tdd-37ueu?file=/src/redditMachine.js

**Additional context**

xstate: 4.9.1
@xstate/react: 1.0.0-rc4

**Comment by wuweiweiwu** [comment] 2020-04-27 23:54
although from initial looking at the source it doesnt seem to be different other than how initial context is inferred

**Comment by wuweiweiwu** [comment] 2020-04-28 00:05
played around with the version of `@xstate/react` seems like only `1.0.0-rc4` is broken `1.0.0-rc3` works

**Comment by davidkpiano** [comment] 2020-04-28 03:09
Duplicate of #1125

**Comment by mattpocock** [comment] 2021-07-19 08:57
@davidkpiano Can this be closed by dint of being a duplicate of #1125?

**Closed** 2021-07-19 09:52 UTC
Labels: bug, duplicate
