### ISSUE TITLE
External self transitions require target to re-enter the state node

### ISSUE THREAD

**Issue by slowselfip** [statelyai/xstate#1885] opened 2021-01-27 12:21 UTC
**Description**

This is regarding the documentation/functionality w.r.t. external self transitions. I'm not sure if I misinterpreted the docs or if it's a bug.

**Expected Result**

The documentation at https://xstate.js.org/docs/guides/transitions.html#external-transitions mentions the following:

> EVENT: { target: undefined, actions: [ ... ], internal: false } - external self-transition

and

> External transitions will exit and reenter the state node in which the transition is defined.

From this I figured something like the following would suffice to re-trigger the entry/exit actions and the invoke on the someState state node when the machine received a SOME_EVENT - event.

```javascript
{
  ...
  someState: {
    entry: 'someEntryAction',
    exit: 'someExitAction',
    on: {
      SOME_EVENT: {
        internal: false
      }
    },
    invoke: {
      src: someService,
      ...
    }
  }
  ...
}
```

To get the expected result I had to add an explicit target in the SOME_EVENT transition config.

```javascript
on: {
  SOME_EVENT: {
    target: 'someState', // <- Here
    internal: false
  }
}
```

**Actual Result**

Neither the entry/exit or invoke occured as I was sending SOME_EVENT to the machine.

**Reproduction**

https://codesandbox.io/s/solitary-dream-oo1cw?file=/src/index.ts

**Additional context**

Tested this on xstate 4.15.4

**Comment by Andarist** [comment] 2021-01-27 18:26
The behavior looks correct - take a look at computeExitSet procedure described here: https://www.w3.org/TR/scxml/#AlgorithmforSCXMLInterpretation

Targetless transitions specifically do not exit any states - we could maybe document this better though. Would you be willing to prepare a docs PR that would make this more clear?

**Comment by davidkpiano** [comment] 2021-01-27 18:27
This is working as intended:

> The exit set of a transition in configuration C is the set of states that are exited when the transition is taken when the state machine is in C. **If the transition does not contain a 'target', its exit set is empty.**

> The entry set of a transition in configuration C is the set of states that are entered when the transition is taken. **If a transition does not contain a 'target', its entry set is empty.**

https://www.w3.org/TR/scxml/#SelectingTransitions

That is, regardless of if `internal` is specified, if there is no target, the state node will not be exited/reentered.

**Comment by slowselfip** [comment] 2021-01-27 19:23
Thanks for clarifying. Like @Andarist mentioned, the docs could maybe be a bit more specific that targetless transitions will lack entry / exit-set (and thus not trigger entry/exit actions etc).

What I felt was a bit confusing was the following:

First it's mentioning "external transitions will exit and reenter the state node in which the transition is defined".

And then in the next section the following are listed:
* EVENT: { actions: [ ... ], internal: false } - external self-transition
* EVENT: { target: undefined, actions: [ ... ], internal: false } - external self-transition, same as above

Which is stating that the above event types are external and per the first definition exit and re-enter the state node which they are defined in.

Is it correct that targetless external self-transitions exit and re-enter their state nodes, but when they do, they do not have any entry / exit-set?

Maybe it's possible to specify that the last two event types are _targetless_ and that _targetless_ external self-transitions will not trigger entry- or exit actions of the parent state node?

**Comment by Andarist** [comment] 2021-01-27 19:38
I would start from adjusting what terms are used there - a targetless transition is not a self transitions, at least not according to this glossary: https://statecharts.github.io/glossary/self-transition.html

**Comment by jlarmstrongiv** [comment] 2023-01-23 03:49
I was following the docs, which described:

```js
import { createMachine } from 'xstate';

const wordMachine = createMachine({
  id: 'word',
  initial: 'left',
  states: {
    left: {},
    right: {},
    center: {},
    justify: {}
  },
  on: {
    // internal transitions
    LEFT_CLICK: '.left',
    RIGHT_CLICK: { target: '.right' }, // same as '.right'
    CENTER_CLICK: { target: '.center', internal: true }, // same as '.center'
    JUSTIFY_CLICK: { target: '.justify', internal: true } // same as '.justify',
    
    // external transitions
    LEFT_CLICK: 'word.left',
    RIGHT_CLICK: 'word.right',
    CENTER_CLICK: { target: '.center', internal: false }, // same as 'word.center'
    JUSTIFY_CLICK: { target: 'word.justify', internal: false } // same as 'word.justify'
  }
});
```

However, when I tried to paste it into [state.ai](https://stately.ai/viz) with only the external transitions, I received the error:

```
ERROR
Child state 'word' does not exist on 'word'
```

Only the `CENTER_CLICK: { target: '.center', internal: false }, // same as 'word.center'` external action did not error.  So it seems external self-transitions do require the target.

**Comment by davidkpiano** [comment] 2023-01-23 03:59
@jlarmstrongiv Are you trying this in stately.ai/viz or stately.ai/editor?

**Comment by jlarmstrongiv** [comment] 2023-01-23 04:30
@davidkpiano 

That was stately.ai/viz

```
ERROR
Child state 'word' does not exist on 'word'
```

But it turns out state.ai/editor also errors with:

```
Import Code

Warning: importing from JSON will overwrite all data in "word"

Failed to parse machine definition
```

Both the editor and viz passed with this id syntax:
```js
{
    // external transitions
    LEFT_CLICK: "#word.left",
    RIGHT_CLICK: "#word.right",
    CENTER_CLICK: { target: ".center", internal: false }, // same as 'word.center'
    JUSTIFY_CLICK: { target: "#word.justify", internal: false }, // same as 'word.justify'
}
```

And failed with this syntax from the docs:

```js
{
    // external transitions
    LEFT_CLICK: 'word.left',
    RIGHT_CLICK: 'word.right',
    CENTER_CLICK: { target: '.center', internal: false }, // same as 'word.center'
    JUSTIFY_CLICK: { target: 'word.justify', internal: false } // same as 'word.justify'
}
```

**Comment by Andarist** [comment] 2023-01-23 11:56
The syntax from the docs is incorrect. The syntax looks like this: `sibling.its_child`. Since this example defines those transitions on the root... it doesn't have any siblings so it shouldn't work. But we had a bug in the target resolution algorithm that should make this work today (this is fixed on the `next` branch though).

I would avoid using this syntax anyway - to stay future-proof. That means that the best resolution to this issue is to fix the docs

**Closed** 2023-09-14 10:51 UTC
Labels: wontfix, documentation, core
