### ISSUE TITLE
Bug: [v4] Using `getSnapshot` before machine is initialized messed up spawned actors

### ISSUE THREAD

**Issue by offirgolan** [statelyai/xstate#4392] opened 2023-10-24 17:32 UTC
### Description

When using `actor.getSnapshot()` before the initial transition, spawned actors in the entry action stay deferred. If you look at the console log in the code sandbox, you'll see that the `entryRef` stays deferred. Replacing the `actorRef.getSnapshot()` with `undefined` in the useEffect fixes it.

### Expected result

Using `getSnapshot()` should not affect spawned actors in entry action

### Actual result

Using `getSnapshot()` breaks spawned actors in entry action

### Reproduction

https://codesandbox.io/s/eloquent-maria-vthtmm?file=/src/index.js

### Additional context

xstate: v4.38.2
@xstate/react: v3.2.2

**Comment by Andarist** [comment] 2023-10-25 08:14
It's an unfortunate byproduct of the old implementation that is quite hard to change right now. This has already been fixed in the upcoming v5.

In v4 you could try to use a helper like this to read the current state of the actor:
https://github.com/statelyai/xstate/blob/e87600ea450fa19b71d2051fac3c6c54fb9d486e/packages/xstate-react/src/utils.ts#L25-L31

The problem is that you read that snapshot before the actor gets started and it only gets started in the `useEffect` in the `Provider` (and that's higher in your React tree so it gets executed after your own effect)

**Comment by offirgolan** [comment] 2023-10-27 17:51
No worries, this isn't a major issue and I'm able to work around it for now 😄

**Comment by Andarist** [comment] 2023-11-15 14:16
Even though this is still an issue - it's pretty impossible to actually fix this in v4 right now. So I'm going to close this for housekeeping purposes. We hope to release v5 very soon and that resolves this issue entirely.

**Closed by Andarist** 2023-11-15 14:16 UTC
Labels: bug
