### ISSUE TITLE
Bug: Sending an event to a service on `exit` triggers an error

### ISSUE THREAD

**Issue by Mxime** [statelyai/xstate#3617] opened 2022-09-26 15:42 UTC
### Description

Since I use `predictableActionArguments: true` as advised in the Actions [documentation](https://xstate.js.org/docs/guides/actions.html), I get an error when I try to send an event from `exit`.

```error
Error: Unable to send event to child 'my-service' from service 'toggle'.
```

### Expected result

I expect `my-event` to have been received by `my-service` upon exiting a state

### Actual result

```error
Error: Unable to send event to child 'my-service' from service 'toggle'.
```

### Reproduction

https://codesandbox.io/s/thirsty-ritchie-yfpzis

### Additional context

xstate 4.33.6

**Comment by Andarist** [comment] 2022-09-26 21:58
Thank you for the report and the repro case. I think that I already see what the problem is, I need to figure out a fix for this though.

**Comment by GuillaumeAmat** [comment] 2022-10-13 07:43
@Andarist did you figure a possible solution here? :pray:

**Comment by Andarist** [comment] 2022-10-13 08:24
Sorry for the delay, I'll take care of this next week

**Comment by Mxime** [comment] 2022-12-19 10:42
It seems [we still face](https://codesandbox.io/s/thirsty-ritchie-yfpzis) the issue with `4.35.0`

**Comment by davidkpiano** [comment] 2022-12-19 13:50
The problem has been identified and we will fix it soon.

**Closed** 2022-12-19 16:10 UTC
Labels: bug
