### ISSUE TITLE
Assign action in entry get a wrong state

### ISSUE THREAD

**Issue by Sczlog** [statelyai/xstate#2415] opened 2021-07-15 02:32 UTC
**Description**
Action in entry will get different state for assign action and non-assign action;
``` typescript
const machine = createMachine<ToggleContext, ToggleEvent>(
  {
    id: "machine",
    initial: "inactive",
    context: {
      count: 0
    },
    states: {
      inactive: {
        on: { TOGGLE: "active" },
        entry: ["assignEntry", "nonAssignEntry"]
      },
      active: {
        on: { TOGGLE: "inactive" },
        entry: ["assignEntry", "nonAssignEntry"]
      }
    }
  },
  {
    actions: {
      assignEntry: assign({
        count: (context, event, { state }) => {
          console.log("assign", state);
          return ++context.count;
        }
      }),
      nonAssignEntry: (context, event, { state }) => {
        console.log("non assign", state);
      }
    }
  }
);
```
**Expected Result**
They should have same state value, I think the state should be the target state, not previous state;

**Actual Result**
They have different state value:
![image](https://user-images.githubusercontent.com/29588646/125718637-708dfffc-002d-4e41-8946-a10c5e2c7391.png)

**Reproduction**
- [CodeSandbox template (TypeScript)](https://codesandbox.io/s/sweet-meadow-dw1yn?file=/src/index.ts)

**Additional context**
xstate version: 4.22.0

**Comment by mattpocock** [comment] 2021-07-21 09:39
@Sczlog Thanks for the repro. This is strange. When the very first assign runs, its state value is undefined.

I assume this is something to do with the batching of assign actions before non-assign actions.

**Comment by mattpocock** [comment] 2021-07-21 09:46
Added a failing test in #2445

**Comment by mattpocock** [comment] 2021-07-21 09:52
This may be working as intended currently, though I'd need an SCXML doyen like @Andarist or @davidkpiano to know for sure.

**Comment by Sczlog** [comment] 2021-07-21 11:11
@mattpocock Thanks for the reply.
I am not sure about the root cause, but I found In `resolveActions` function it will process actions first and group them by assign action and other action first,
then it will `updateContext` by assign action first. No matter the assign action is assigned in entry or actions.
I think we may need split assign action by entry action and normal action and only do normal assign action in the start of `resolveActions`?
IMO the order should be like this one:
normal assign action -> normal other action -> entry assgin action -> entry other action?

**Comment by davidkpiano** [comment] 2021-07-21 19:01
> @mattpocock Thanks for the reply.
> I am not sure about the root cause, but I found In `resolveActions` function it will process actions first and group them by assign action and other action first,
> then it will `updateContext` by assign action first. No matter the assign action is assigned in entry or actions.
> I think we may need split assign action by entry action and normal action and only do normal assign action in the start of `resolveActions`?
> IMO the order should be like this one:
> normal assign action -> normal other action -> entry assgin action -> entry other action?

You can now add `.preserveActionOrder: true` in the root machine config to resolve this.

**Comment by Sczlog** [comment] 2021-07-22 03:27
@davidkpiano 
I updated my repro with `preserveActionOrder:true` in the config but I still get a wrong state here.
![image](https://user-images.githubusercontent.com/29588646/126586255-f1f04eea-44c9-4628-910c-56f03ce6b378.png)
![image](https://user-images.githubusercontent.com/29588646/126586265-ddb6ad65-b2c8-44fe-8cf1-0c654d4b0aa9.png)

**Comment by Andarist** [comment] 2021-07-22 10:17
Note that "direct assign" is just a transition action, non-`assign` one. Unless I've missed something here - this has nothing to do with `assign`.

Q1: in your opinion, what's the "correct" state in here to be received?
Q2: why do you want to access state in an action? what's your use case?

**Comment by Sczlog** [comment] 2021-07-26 08:08
@Andarist 
Sry I didn't check message for a few day.
Q1: I am not sure which one is the correct state, but I think they should be the same one? I declare them in the same entry actions array and I suppose they get the same meta data. And for me, I think it should be equal to the state I set in direct assign.
Q2: I want to know my target state node, I want assign a property in my context by the target node's value. So I suppose I can assign it at the entry action, by `meta.state.value`, but I found that I got  the previous state node. When the non-assign get the entered state node.

**Comment by Andarist** [comment] 2021-07-26 11:43
> Q1: I am not sure which one is the correct state, but I think they should be the same one? I declare them in the same entry actions array and I suppose they get the same meta data. And for me, I think it should be equal to the state I set in direct assign.

I would say that in this case, you don't actually need what is currently provided as `state`. You need some kind of a representation/reference to the state **node** on which a particular action is defined. Would that be correct?

> Q2: I want to know my target state node, I want assign a property in my context by the target node's value. So I suppose I can assign it inside the entry action, by meta.state.value, but I found that I got the previous state node. When the non-assign get the state node entered

Could you explain how do you want to utilize that on a more concrete example? Maybe there is a better way to handle this requirement.

**Comment by Sczlog** [comment] 2021-07-28 02:18
@Andarist
I am making a event matching machine, it receive native dom event and transfer it to the user interaction on the website.
I use native events as xstate event and current interaction type(like click, drag, keydown and etc) as statenode. And store detailed info in the context.
The code is here:
https://github.com/Sczlog/interaction-recorder/blob/optimize-matcher-event/src/matcher/machine.ts
I am making a workaround by using internal `_transition` function to get target node which I think not correct.

**Comment by Andarist** [comment] 2021-07-28 09:14
I'm not yet convinced that we should expose the target state there anyhow - mainly because it might doesn't end up being the actual target when you consider parallel states which come with target deconflicting.

As a workaround you could do this:
```js
actions: ['emitStep', { type: 'newStep', target: 'xxx' }],
```
This should be available in the `assign`'s implementation like this:
```js
assign((ctx, ev, { action }) => {
  // do something with `action.target`
  return {}
})
```

Please also note that it's highly discouraged to perform any side-effects within `assign` and I've seen that you are emitting some events there.

**Comment by Sczlog** [comment] 2021-07-28 10:01
@Andarist 
Got it. It seems work well in my app.
But I still feel confused about the difference value of state between assign action and non-assign action in the same entry array, it that epxected?

**Comment by Andarist** [comment] 2021-07-28 10:49
> But I still feel confused about the difference value of state between assign action and non-assign action in the same entry array, it that epxected?

Not quite but this mismatch is there long enough that it would be a breaking change to fix this at the moment. We will be fixing this in the next major release (v5) but we might also introduce a new meta property that would describe the state in which a particular action is defined.

**Comment by pke** [comment] 2021-09-14 22:29
I wanted to add, that the `meta.state.value` in `entry` assign actions still points to the previous state. This doesn't seem right.

**Comment by veeramarni** [comment] 2023-07-29 22:29
Any update on this issue? It is been open for a while, this issue is seen when `assign` is used.

**Comment by davidkpiano** [comment] 2023-09-07 04:22
> Any update on this issue? It is been open for a while, this issue is seen when `assign` is used.

We plan on refining what is available in `v5` for "state info", and we probably won't provide the entire `state` in there. This is still being worked on (cc. @Andarist)

**Comment by Andarist** [comment] 2023-09-07 08:26
I think that this one was largely addressed in v5. For starters, we definitely have access to the same data in different action types since we no longer prioritize any of them and all of them are just executed "in order". The `lightNode` + `entry` actions solve @Sczlog's issue (see the answer to Q2 [here](https://github.com/statelyai/xstate/issues/2415#issuecomment-886475918)). The same mitigates @pke's problem.

**Closed** 2023-09-07 11:58 UTC
Labels: core
