### ISSUE TITLE
[V5] [Bug]: typescript errors when spawning actors during context initialization

### ISSUE THREAD

**Issue by bhvngt** [statelyai/xstate#4566] opened 2023-12-07 10:33 UTC
## Bug or feature request?
Bug

## Description:
When I am trying to spawn an actor during context initialisation, typescript throws an incorrect error linking one of the invokable actors with spawned actor.

## (Bug) Expected result:
It should not throw any typescript error

## (Bug) Actual result:
![image](https://github.com/statelyai/xstate/assets/79074469/55324eca-85a5-4125-8d96-a061ee4d493e)

## Link to reproduction:
https://stackblitz.com/edit/xstate-v5-bug?file=package.json,src%2Fcounter.ts

## Additional context
I could not find any `Bug` template for filing bugs. Hence I have filed this using a blank template.

**Comment by Andarist** [comment] 2023-12-07 14:52
There are some issues with this code. if you `setup` concrete actor types then you shouldn't use `Child` directly with `spawn`. Instead, you should reference it with a string (`spawn('Child')`). So you should also actually setup this one since right now you are only setting up `two`.

That being said - even with that fix it doesn't work with TS 5.0. Our types rely currently on a pattern enabled by TS 5.1 ( ps://github.com/microsoft/TypeScript/pull/53098 ). I prepared a fix for this [here](https://github.com/statelyai/xstate/pull/4568) so soon it should also work with TS 5.0

You can see the working example here: [TS playground ](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAbzgMyhEAFNJgGcCmANHAIa67ADmAdsQTAK5jECC5V1LAxjMBLXG4xoAJXzIAYtjgBfFNIBEAD1wwSMfAoDccAPS64MAJ5h8uAFxwArADoAjDYAMAKGdd+qwwHcIcALzy6FjoePgAFGEAlP4AfHDBOAQ2UGYQADYAbuEATJGRWm4e8MDUXABCRv6k7DQRSO7UGkrwMsRgJFAkIBZw1AwgAEb4UNF+cQjOcHApjFDUiHDuDI2WDU0wNkuNcADUcO2d3bIFMtFkgjWcPHzUADwk1EbED0+kj8-vb0YxBYXUngBhAAWwDSABMqvQmGEEKdNil1PgALIkLgg6jhCZTErAXgkNKWBQsBSESZwVSInpYqaCSyw0lTVrOU6-KFgGFk4ymKlkqZrfDNOlyc71EHgyxCUTiKToW5c-AQZBwYGgsE-RYQZYwSx9QbDWQMmn4LKNKnC3ALeWEgAiAEkAMosMoAGQAogpZHAAD6Wkz4QksAEAFVtADUWEH3QayUypqjhFAeTTvBBDVMVeDDbHSNcPHS4CVypUmXCuAiNCi0SVMWTgGDCSBUejNIacXiCXAFCV48AsiSyfzBXAYeT2l55qdYsPRarLLgx9QwgoM2CFJFiFttXBHLJ17XqBkIABrf0LXBQLiEmA+D3Z-CNKBGfNWzuFiok-YdLo9bLRqYUjQkxpbtriyIU0xzXgMnUEpKHA3lIN7U96RjUkWWcIA)

I also wouldn't recommend doing this:
```ts
const incBy = assign(({ context }, params: number) => {
  return { count: context.count + params };
}) as AssignAction<any, any, any, any, any>;
```

While you declared the `params` type within this declaration you essentially forget it by casting to `AssignAction<any, any, any, any, any>`. This might actually lead to problems because now `params` won't be type-checked correctly and they won't error when you try to use the incorrect ones: [TS playground](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAbzgMyhEAFNJgGcCmANHAIa67ADmAdsQTAK5jECC5V1LAxjMBLXG4xoAJXzIAYtjgBfFNIBEAD1wwSMfAoDccAPS64MAJ5h8uAFxwArADoAjDYAMAKGdd+qwwHcIcALzy6FjoePgAFGEAlP4AfHDBOAQ2UGYQADYAbuEATJGRWm4e8MDUXABCRv6k7DQRSO7UGkrwMsRgJFAkIBZw1AwgAEb4UNF+cQjOcHApjFDUiHDuDI2WDU0wNkuNcADUcO2d3bIFMtFkgjWcPHzUADwk1EbED0+kj8-vb0YxBYXUngBhAAWwDSABMqvQmGEEKdNil1PgALIkLgg6jhCZTErAXgkNKWBQsBSESZwVSInpYqaCSyw0lTVrOU6-KFgGFk4ymKlkqZrfDNOlyc71EHgyxCUTiKToW5c-AQZBwYGgsE-RYQZYwSx9QbDWQMmn4LKNKnC3ALeWEgAiAEkAMosMoAGQAogpZHAAD6Wkz4QksAEAFVtADUWEH3QayUypqjhFAeTTvBBDVMVeDDbHSNcPHS4CVypUmXCuAiNCi0SVMWTgGDCSBUejNIacXiCXAFCV48AsiSyfzBXAYeT2l55qdYsPRarLLgx9QwgoM2CFJFiFttXBHLJ17XqBkIABrf0LXBQLiEmA+D3Z-RwAACMFwAFoBaYeG+oGgoGT8I0oCMfMrU7QsKhJfYOi6HoFCDAAJB04EQ20ADkAQAeREERXWDW9DQpDQkxpbtriyIU0xzXgMnUEpKHI3lKN7U96RjUkWWcIA)

To fix this it's best to declare your `assign` "inline", within `setup` itself. This enables the types to flow from context into this `assign`. You can see this in practice here: [TS playground](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAbzgMyhEAFNJgGcCmANHAIa67ADmAdsQTAK5jECCAxjNAEr7IBi2OAF8UggEQAPXDBIx8YgNxwA9MrgwAnmHy4AXHACsAOgCMRgAwAoS2wjVp6gO4Q4AXlHos6PPgAUvgEo3AD44LxwCIygdCAAbADc-ACYAgIVrW3t4AGEAC2BYgBM3OHomXwQhAKM2aNl8AFkSNnzqPwRLODhgamAYYBJY-TEWMUJO0pk5PUQJrpZ9SvGuoXGq9MsysAqJzW0Zjq6uzLkJGEWRMkQ4FoLC-XZOKB5+bAAePfwIZDg8u+ClLYGNRznBqAwQAAjfBQYTLI74RIgg6XXDXT7DAAiAEkAMosABCABkAKJiYRwAA+6K0+GGLGyABVsQA1FiMslwiarCbNJ4HOZOCDwrp-IrwnldPnAOwCo7dahsAkafRkCg0fxIE74M5wuBgEhQEggGbgqEwoKuUKHeVwaKMKDUa5AkH6bVnGoQYHwADU+sNxrRQnS8qqErW1Vq+HqTVubR2XWA9zgYhAzVa8nhPT6AyGKZ60sSYwm7tBFVKBscTqqITg5duRX0uEr1F8YjFhTEAWILtB5mE3YmPXiEAA1nTrrgoGxhjBnOTJSo1AABGC4AC0Ou0HE3UDQUAm+BBUBVNO0wx6So0Y39RpNw0ZAAk8XAX9iAHLZADyXC4JKZC7wtI9RykcBYcMAiQXCKpAQfEsg9JQ0GCoWE5LNyEbpEAA)

**Closed** 2023-12-07 15:31 UTC

**Comment by bhvngt** [comment] 2023-12-07 16:09
Thanks @Andarist as always for your detailed explanation. In the hindsight it make sense to treat `spawned actors` the same way as `invoked actors`. 

> That being said - even with that fix it doesn't work with TS 5.0. Our types rely currently on a pattern enabled by TS 5.1 ( https://github.com/microsoft/TypeScript/pull/53098 ). I prepared a fix for this https://github.com/statelyai/xstate/pull/4568 so soon it should also work with TS 5.0

My reproduction uses TS 5.3. I can see that the error goes away in the TS playground when 5.3 is chosen. Not sure, why it is showing the error in stackblitz in spite of the latest typescript version. I get the same problem in my local setup too.

> To fix this it's best to declare your assign "inline", within setup itself. This enables the types to flow from context into this assign. You can see this in practice here: [TS playground](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAbzgMyhEAFNJgGcCmANHAIa67ADmAdsQTAK5jECCAxjNAEr7IBi2OAF8UggEQAPXDBIx8YgNxwA9MrgwAnmHy4AXHACsAOgCMRgAwAoS2wjVp6gO4Q4AXlHos6PPgAUvgEo3AD44LxwCIygdCAAbADc-ACYAgIVrW3t4AGEAC2BYgBM3OHomXwQhAKM2aNl8AFkSNnzqPwRLODhgamAYYBJY-TEWMUJO0pk5PUQJrpZ9SvGuoXGq9MsysAqJzW0Zjq6uzLkJGEWRMkQ4FoLC-XZOKB5+bAAePfwIZDg8u+ClLYGNRznBqAwQAAjfBQYTLI74RIgg6XXDXT7DAAiAEkAMosABCABkAKJiYRwAA+6K0+GGLGyABVsQA1FiMslwiarCbNJ4HOZOCDwrp-IrwnldPnAOwCo7dahsAkafRkCg0fxIE74M5wuBgEhQEggGbgqEwoKuUKHeVwaKMKDUa5AkH6bVnGoQYHwADU+sNxrRQnS8qqErW1Vq+HqTVubR2XWA9zgYhAzVa8nhPT6AyGKZ60sSYwm7tBFVKBscTqqITg5duRX0uEr1F8YjFhTEAWILtB5mE3YmPXiEAA1nTrrgoGxhjBnOTJSo1AABGC4AC0Ou0HE3UDQUAm+BBUBVNO0wx6So0Y39RpNw0ZAAk8XAX9iAHLZADyXC4JKZC7wtI9RykcBYcMAiQXCKpAQfEsg9JQ0GCoWE5LNyEbpEAA)

Got it. I do have few common use cases where I would prefer to use shared actions such as `storeError`, `resetError` etc. I understand that I will loose the type safety for those actions. I guess as long as they are few and clear, it should be alright!!

**Comment by Andarist** [comment] 2023-12-07 16:15
> Not sure, why it is showing the error in stackblitz in spite of the latest typescript version.

My bet is that it doesn't really use the TS version installed by your project there but rather whatever they have bundled with their editor.

> I get the same problem in my local setup too.

Could you try using "Select TypeScript version..." from your command palette (I'm assuming that you are using VS Code) and use the workspace version?

**Comment by bhvngt** [comment] 2023-12-07 16:40
> My bet is that it doesn't really use the TS version installed by your project there but rather whatever they have bundled with their editor.

I guess you are right.

> Could you try using "Select TypeScript version..." from your command palette (I'm assuming that you are using VS Code) and use the workspace version?

I am using Jetbrains. I found a small typescript issue with my code. On fixing that the error in my local setup is gone.

Thanks @Andarist.

**Comment by davidkpiano** [comment] 2024-03-15 17:56
@karlanke Currently, if you specify known `actors` in `setup(…)`, you can only reference those actors in `spawn`.

Maybe we can find some way to loosen this constraint (cc. @Andarist)

**Comment by karlanke** [comment] 2024-03-15 19:07
Is there an easy way to do that dynamically? I took a quick stab at it and it didn't immediately accept a
```
actors: {
userActor,
...dynamicActors
}
```
but admittedly I didn't spend a lot of time on it.

As a workaround, for anyone who finds this, that constraint seems to disappear if you provider input to the actor being spawned.

 I don't think this is a huge useability problem, since the actor can still be typed fully, but glad to know what the cause is.

**Comment by davidkpiano** [comment] 2024-03-15 19:21
@karlanke Let's open a separate issue for this, so it doesn't get lost 🙏

**Comment by Wenemy** [comment] 2025-01-01 07:40
//@ts-expect-error for now?
