### ISSUE TITLE
TypeScript bug with the new createModel() functionality

### ISSUE THREAD

**Issue by VanTanev** [statelyai/xstate#2036] opened 2021-03-25 12:34 UTC
**Description**
When creating a machine with `createModel()` as basis and writing the definition, when you start writing the `events` creators, but before you have added any events, you get a cryptic error message in TypeScript:

```typescript
const toggleModel = createModel(
  { count: 0 },
  {
    events: { }
  }
)

const machine = createMachine<typeof toggleModel>({
  context: {
// No overload matches this call.
//   Overload 2 of 2, '(config: MachineConfig<Model<{ count: number; }, never, FinalModelCreators<{ events: {}; }>>, any, AnyEventObject>, options?: Partial<...>): StateMachine<...>', gave the following error.
//     Type '{ count: number; }' is not assignable to type 'Model<{ count: number; }, never, FinalModelCreators<{ events: {}; }>> | (() => Model<{ count: number; }, never, FinalModelCreators<{ events: {}; }>>)'.
//       Object literal may only specify known properties, and 'count' does not exist in type 'Model<{ count: number; }, never, FinalModelCreators<{ events: {}; }>> | (() => Model<{ count: number; }, never, FinalModelCreators<{ events: {}; }>>)'  
// The expected type comes from property 'context' which is declared here on type 'MachineConfig<Model<{ count: number; }, never, FinalModelCreators<{ events: {}; }>>, any, AnyEventObject>'  
    count: 0
  },
});
```

Adding a single definition to the `events` creators param removes the error, but as long as no events are defined, you will get this. It was very confusing to me, and I went back and forth on my code for half an hour before I found out I had to add an event creator for the error to go away.

**Expected Result**
The above code should not produce TypeScript errors.

**Actual Result**
Typescript throws errors if the `events` creator argument to `createModel()` is empty.

**Reproduction**
https://codesandbox.io/s/kind-meadow-t9tje?file=/src/index.ts

**Additional context**
```
xstate@4.17.0
typescript@4.2.3
```

**Comment by davidkpiano** [comment] 2021-03-25 13:27
Workarounds:

1. Add an event (like you mentioned):

	  ```ts
	  const toggleModel = createModel(
	    { count: 0 },
	    {
	      events: {
	        TOGGLE: () => ({})
	      }
	    }
	  );
	  ```
2. Remove the empty events:

	  ```ts
	  const toggleModel = createModel(
	    { count: 0 }
	  );
	  ```

**Comment by Andarist** [comment] 2021-03-25 13:29
Note that the presented snippet here **doesn't** result in an error. The code on the codesandbox, on the other hand, errors. 

Those transitions defined for non-existent events trips the first overload of `createMachine` so TS tries the second overload (we can't stop it from doing that AFAIK) and then it results in a very cryptic error since the second overload is totally different from the first one.

**Comment by VanTanev** [comment] 2021-03-25 14:56
@Andarist This is weird.
Locally, an equivalent snippet (no transitions defined) does error, but when I copy it to CodeSandbox it no longer does.

![image](https://user-images.githubusercontent.com/202527/112492871-52dab400-8d8a-11eb-9892-98b1e89ec45c.png)

**Comment by davidkpiano** [comment] 2021-03-25 15:03
What versions of TypeScript are being used in the reproductions?

**Comment by VanTanev** [comment] 2021-03-25 15:09
@davidkpiano `typescript@4.2.3`

Actually, locally even this fails:
![image](https://user-images.githubusercontent.com/202527/112495551-aa7a1f00-8d8c-11eb-94f0-175bc6273f1e.png)

I'm at a loss. 
The context is a `create-react-app`, but it shouldn't matter.

```bash
$ tsc --showConfig
{
    "compilerOptions": {
        "target": "es5",
        "lib": [
            "dom",
            "dom.iterable",
            "esnext"
        ],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noErrorTruncation": true,
        "noEmit": true,
        "jsx": "react-jsx",
        "baseUrl": "./src"
    },
}
```

**Comment by VanTanev** [comment] 2021-03-25 15:23
@davidkpiano @Andarist created a reproduction repo for the stuff described in my previous comment: https://github.com/VanTanev/xstate-2036-reproduction/blob/main/src/index.tsx#L14

**Comment by Andarist** [comment] 2023-02-07 13:47
This is related to the model API that is already deprecated for some time. Therefore I think it's OK to close this issue. If you have any typing issues with the main `createMachine` API - let me know and I will try to assist you as much as I can.

**Closed by Andarist** 2023-02-07 13:47 UTC
Labels: typescript, has workaround
