### ISSUE TITLE
Bug: There is some typescript mismatch

### ISSUE THREAD

**Issue by richtera** [statelyai/xstate#3256] opened 2022-04-27 22:27 UTC
### Description

I have been using xstate for a while and I had to put override aliases for certain paths into my tsconfig in order to make it pickup the correct types. I have recently upgraded to latest and testes whether I can remove the strange aliases, but they are still required.
In order to be able to use all of xstate actions I have to alias the es modules back to lib.

My tsconfig.json contains
```javascript
"paths": {
      .
      . ,,, more aliases here
      .
      "@xstate/react/es": ["node_modules/@xstate/react/lib"],
      "xstate/es": ["node_modules/xstate/lib"]
    }
```

If I remove the alises I end up with the errors in "Actual result"

### Expected result

It should just work without those aliases.

### Actual result

Many many errors like this: 
```
Type 'import("/home/andy/Development/nx-workspace/node_modules/xstate/lib/types").ConditionPredicate<any, import("/home/andy/Development/nx-workspace/node_modules/xstate/lib/types").DoneInvokeEvent<any>>' is not assignable to type 'import("/home/andy/Development/nx-workspace/node_modules/xstate/es/types").ConditionPredicate<any, import("/home/andy/Development/nx-workspace/node_modules/xstate/es/types").DoneInvokeEvent<any>>'.
                                                    Types of parameters 'meta' and 'meta' are incompatible.
```

### Reproduction

https://codesandbox.io/s/hardcore-kare-ty3qr8

### Additional context

What's interesting is that initially I got exactly the same error in the sandbox, but I think the sandbox doesn't always do full typechecking so the error later goes away. The error shows up when trying to use the matching because pure was imported from lib and all the other actions from xstate directly. I think the fix would be to export pure from xstate so we wouldn't need to import things from the lib folder at all and the types would match.

**Comment by Andarist** [comment] 2022-04-28 09:06
The given repro case doesn't have any error (apart from a syntax error that I had to fix). Could you recheck if you have saved your codesandbox?

Do you ever intentionally import something from `xstate/es`? That should be avoided.

> The error shows up when trying to use the matching because pure was imported from lib and all the other actions from xstate directly.

This shouldn't matter because even if the runtime code is being pulled from `xstate/es`, what TypeScript actually sees there is `xstate/lib`.

**Comment by richtera** [comment] 2022-04-28 09:11
No when importing things from xstate it automatically uses the es folder but pure is not available as an export from xstate and has to be imported from lib. By redirecting all imports to xstate through the lib folder I was previously getting this to work. When setting up the sandbox it initially show exactly the same errors I get locally without my alias hack, but after I shared the URL it stopped showing the error altogether even though pure is still imported from lib. Note that the pure usage in the sandbox is obviously contrived just to show the error.

**Comment by richtera** [comment] 2022-04-28 09:13
I will recheck where the es usage comes from but I think my webpack setup prefers the es folder

**Comment by mattpocock** [comment] 2022-04-28 09:13
@richtera Pure needs to be imported from `actions`, as far as I remember:

```ts
import { actions } from 'xstate'

actions.pure
```

**Comment by richtera** [comment] 2022-04-28 09:17
Ah I will try that

**Comment by Andarist** [comment] 2022-04-28 09:17
> I will recheck where the es usage comes from but I think my webpack setup prefers the es folder

Yes, webpack (and other bundlers) should prefer it - but this **only** applies to the runtime code, not to the typings. Note that `xstate/es` has its own types (duplicate of what you can find in `xstate/lib`) but to have those loaded somehow you would have to **explicitly** import something from `xstate/es`.

**Comment by richtera** [comment] 2022-04-28 09:36
It looks like there is a similar problem with import { MaybeLazy } from '@xstate/react/lib/types';

**Comment by Andarist** [comment] 2022-04-28 09:47
This is rather an internal type - so I wouldn't recommend using it in your own projects (we might hide it from the public-available imports in the future)

**Comment by richtera** [comment] 2022-04-28 09:49
I am using it to match your API when declaring a custom use or with function but I think I can discontinue using it.

**Comment by richtera** [comment] 2022-04-28 09:56
The UseMachineOptions requires me to defined a duplicate in order to remove the dependency. That's probably more important.

**Comment by richtera** [comment] 2022-04-28 09:59
> > I will recheck where the es usage comes from but I think my webpack setup prefers the es folder
> 
> Yes, webpack (and other bundlers) should prefer it - but this **only** applies to the runtime code, not to the typings. Note that `xstate/es` has its own types (duplicate of what you can find in `xstate/lib`) but to have those loaded somehow you would have to **explicitly** import something from `xstate/es`.

I am pretty sure that when using nx.dev it uses the same code paths for types and webpack, but I could be wrong.  But when I look in visual studio the imports are coming from xstate/es.

**Comment by Andarist** [comment] 2022-04-28 10:02
Could you share a repository showcasing the problem? I would really love to understand the setup that you are using to figure out the best course of action here.

**Comment by richtera** [comment] 2022-04-28 10:13
I put the sandbox code into an nx.dev project here: https://github.com/getselfstudy/xstate-test

**Comment by richtera** [comment] 2022-04-28 10:15
In visual studio you'll see the error in app.tsx
![image](https://user-images.githubusercontent.com/708186/165730937-944062b2-862d-48b8-bfd9-c2380ee78564.png)

**Comment by richtera** [comment] 2022-04-28 14:27
Were you able to access the repo and see the error? I think it reproduces the difference between types coming from xstate and those coming from xstate/lib, but please let me know if it doesn't quite display the problem in a useful way.

**Comment by richtera** [comment] 2022-04-28 15:09
I did but it's the other link. But in the sandbox the typescript error is being ignored after you reload it. Putting the same code inside of visual studio correctly reproduces the problem every time.

**Comment by Andarist** [comment] 2022-04-28 17:02
This particular problem can be reproduced somewhat easily, see the [TS playground](https://www.typescriptlang.org/play?ts=4.6.2#code/JYWwDg9gTgLgBAbzgQwM6uAcwHYBo4DGUApsjMQLLIEAWw2xcAvnAGZQQhwBEAHqjDLFuAbjgB6cXBgBPMMVQAuOABYAdAGYAjGoAMAKFCRYiOGACuJZmw5c+AoeIA2wAEbjqMYBGypREqVl5JVVNHQNDbHIoVmpGABUITEwnYgBhH3JeeAR9OEIIcyjlbHMQV2IoETzpBRhlVwgIVORsaqZ9fSCEpJTiAFEAN2IouABeRBru5W54gHkAcQWAGX7RfSZq-SJScipaemIAHkTk1Iyo4mz8U76hkZgAPgAKGoQmXDea-M9vX2VcvkgbUBMoLCRns8CJkrjAAJTjR6TYHAkgwSzYOAAbTQGBwkOhl2yCLGSOeSHIoOkUHMjCYcLhAF1qijmHDPsCPjUOnDqkA). It doesn't have to do anything with the `xstate/lib` vs `xstate/es` stuff though - so perhaps you were observing some other problem before.

It seems that `pure` has some inference problems and that it doesnt "pass" its generics to the action objects returned by it.

**Comment by richtera** [comment] 2022-04-28 18:06
Oh cool. That TS playground is a lot better then. I am seeing similar errors all over the place when I don't have the weird aliases of es to lib, but I have removed those alises and changed to importing actions and using actions.pure for example. This kind of solves the problem, but in visual studio, when trying to use pure it will suggest importing it from xstate/lib/actions which then re-introduces the problems. Especially in a nx.dev project this leads to a lot of errors that are kind of visible as warnings, but will cause builds to completely fail is tsc does full type validations. So I think this may not be exactly the thing this is reproducing. What I did find from a comment @Andarist was that if there is one reference to react/es anywhere in the project I do get different errors than if not. So it's possible that having that one import was distorting my environment enough to show unexpected errors although the pure() inference problem is where this path down the rabbit hole started. I am now using just exports from xstate and things seem fine again.

**Comment by richtera** [comment] 2022-04-28 18:19
Ok that was it. I found a verbatim reference to xstate/es in one of my files. Deleting that reference and making it xstate repairs the whole thing. No more patches required at all. That was unexpected for sure. But awesome! I think this solves my issue.

**Comment by Andarist** [comment] 2022-04-28 21:30
I'll close this issue then - although the inference problem related to `pure` is still an issue. That could be reported as a new issue.

**Closed by Andarist** 2022-04-28 21:30 UTC
Labels: bug, typescript

**Comment by richtera** [comment] 2022-04-29 02:30
Thank you. BTW the TS playground it pretty cool and does show the same kind of thing. Very cool. Thanks for your help.

[TSPlayground](https://www.typescriptlang.org/play?ts=4.6.2#code/JYWwDg9gTgLgBAbzgQwM6uAcwHYBo4DGUApsjMQLLIEAWw2xcAvnAGZQQhwBEAHqjDLEA9MVTcA3HGHC4MAJ5gxALjgAWAHQBmAIwaADAChQkWIjhgAriWZsOXPgKHCANsABGw6jGARs4qRk5RRV1bT0jY2xyKFZqRgAVCExMF2IAYT9yXngEQzhCCEto1WxLEHdiKAl8uTEYVXcICDTkbBqmQ0MFJTgklLSAUQA3Ymi4AF5EWp7iVW4EgHkAcWWAGUHJQyYawyJScipaemIAHn7UjKziHPwLodHogD4AClqEJlx32oLvX39VHkCsC6gJVFYSC8XgRrjkAJSTJ7TEEgkgwazYOAAbTQGBwUJh0RuMAREyRLyQ5DBciglkYTDhcIAujUUcw4V8QZ9ap04TUgA)
