### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by huan** [statelyai/xstate#2880] opened 2021-12-18 09:52 UTC
**Description**

When a child machine has been in a state with the `exit: sendParent` action set, if the parent machine stop, then the error will be thrown.

I guess this is because the parent has been destroyed before the child.

**Expected Result**

The interpreter should be stopped gracefully. (executed all the `exit` from all children before destroy parent?)

**Actual Result**

```
TypeError: Cannot read properties of undefined (reading 'name')
```

**Reproduction**

https://codesandbox.io/s/loving-sutherland-y3he8?file=/src/index.ts

**Additional context**

- https://github.com/statelyai/xstate/issues/2057

**Comment by Andarist** [comment] 2021-12-18 10:43
I can confirm that this is a bug - and most likely a duplicate of another issue. I will try to look into this after the weekend as I already exactly know what happens, just need to figure out the most appropriate solution and write tests for this and related scenarios.

**Comment by Andarist** [comment] 2022-01-01 00:04
Just an update - I'm implementing a fix for this, should open a PR in a couple of days. The issue/fix is somewhat delicate so I'm making sure to cover as many edge cases as I can.

**Comment by ptaranto** [comment] 2022-02-15 15:16
Hey @Andarist any update on this?

I'm having the issue when sending an event from child to grandchild machine, here is a CDS for it: https://codesandbox.io/s/elastic-sound-tuv3nk?file=/src/App.tsx

when stoping the parent machine by clicking the button there's another error related to not being able to read `listeners`
to reproduce the original error related to this issue, it'll occur whenever you change the code in `App` and CDS hot reload happens

**Closed** 2022-08-02 08:14 UTC
Labels: bug
