### ISSUE TITLE
Completions incorrect from Typescript "User" example

### ISSUE THREAD

**Issue by hiaux0** [statelyai/xstate#2431] opened 2021-07-18 16:55 UTC
**Description**

I went through some guides, and wanted to check out the Typescript completions capabilities ([User example](https://xstate.js.org/docs/guides/typescript.html#typestates)).

Here is a [TS playground (link)][1] with code copy pasted from said guide
However, I encountered 2 issues
1. Bug(?) in line 67
  ![image](https://user-images.githubusercontent.com/30693990/126075456-a4544c55-d494-4377-95e8-e88199270899.png)
2. Feature Request for line 70 (should I create a new issue?)

**Expected Result**

Re 1. Only "FETCH", ie. `UserEvent` keys show up.

Re 2. The state keys show up, eg. "idle" or "loading
- related to #2425?

**Actual Result**

Re 1. See screenshot above

Re 2. No such completion shows up

**Reproduction**
[TS playground (link)][1]

**Additional context**

Version: I believe the TS playground used the latest version of xstate

Re 2. 
- I digged into the .d.ts files, and tried out to pass an object as args also with not the desired completion.
- I searched for "transition autocomplete" in the Issues, but the one hit, was not relevant to my problem.

[1]: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOE7KMdeAXzgDMoIQ4ByADwGcYs0HANwAoEVTRQm+NHACqPSYhFw4xDCDQAuOHygkA5qPpiJUmfMVQAwhGLYu8BCrgBXKwH4dCyaNWTWKC9dGH1iIxETERgATzBZHygAUQA3NHs4AF4XAB9EOFj4nQ4AMSSAFWsACWFKABMdPUM4E1U8pELtTgAlJIBlAHkAGQA1JNr3SW8rFtz8zuLegCkk63LagOhG0Ob6UWi4hKs+-mwsuedVK7gUjAAbVy6OYDq7wT9rlDsHGGnJW3saEccAAZMpPldJlAdK5iHU0EwSGg6h8IZtoW44QikSiXNc9njZm1wZ9bg8nncIBg6oZhITVMhvkDfpZ-kzHKiiXB2vSbvdHsUeK5kMg0DweHSIYzAY4-jZ2fAwUgoXKhHB0TCsYjSHUWpzWtySdcyQLONJgA90JLPtKfnKAT9QfkVZj4drkWqNSEwgY9YSCSJpXw3FY8IQkVkUOgBGGiKQADyJB3MiiJVLpGCp46nNAAPgAFJd6sUoRwyC4SMAYMB7sUXm8yy4+AIeDoi6p61121cAPQAKjgADph3A+z3-eXrpTqYY27z+0OR2OJ4ShSKxa2jb2B8PB6Px-jJ1dzZau-Od0uD1d6Eeb5EAJT7IPwKF9SQpYCiyNmWhoGD5qFYyRR8xFfd9PzQQchQAIx4VBgGgtB83zZtsHvLJcxJYAmDgFCc0HEAsEIMV8w4NdRXFDh73Q7sex7ZhWHYGACCOSQTgEApDlQ8g4AAAyhXi4AAdwtO44EQuA3RxVd8NtZlByhQd1E0D4THoECRDoiFtJ03SbjgAxgDSHgCggCA4EI4gYm9QwTKYaAvnAN5qzsHgPBEQD8DjSDQgwYgeCrYA7FIzsy3mQ5ijKSoahaDStL0vSUjgABJYSIFcO5dTuYAAGtZBgcyCAwNJHLAZygv85gHIAIk7aqKGq6caXCer1RgZA9xY9BcIwHKMBCFt70HDzQy8pFB18-zAuCjgwo6CLOCi6oOFi-YRCBSBYHyeggA

**Comment by mattpocock** [comment] 2021-07-21 09:29
@hiaux0 

https://www.loom.com/share/4e7b1b7f85f342639db8a045815fb7d6

I'll add a docs PR to fix this.

**Comment by mattpocock** [comment] 2021-07-21 09:30
In fact, ignore the docs PR. The example is actually working and typechecking fine, but the event types you were passing in the TS playground were incorrect. Closing, working as intended.

**Closed by mattpocock** 2021-07-21 09:30 UTC
