### ISSUE TITLE
Bug: Transition on a raised event receives an incorrect event

### ISSUE THREAD

**Issue by rlaffers** [statelyai/xstate#3059] opened 2022-02-17 11:44 UTC
### Description

Here is the example from the docs regarding the `raise` action creator. I have added an action to log the received event:
https://stately.ai/viz/c7d1382e-4009-4962-b24a-e9fca185cadc

When a RAISE event is sent to the machine, the event received in the on "NEXT" transition is "RAISE". This seems incorrect and counter intuitive to me. Is this a bug, or works as expected?
```javascript
middle: {
      on: {
        NEXT: {
          target: "last",
          // this will log "RAISE" ?!
          actions: (ctx, event) => console.log(event.type),
        },
      },
    },
```

### Expected result

My expectation was that the action logs "NEXT".

### Actual result

It logs "RAISE", even though the action is within a transition for "NEXT" event.

### Reproduction

https://stately.ai/viz/c7d1382e-4009-4962-b24a-e9fca185cadc

**Comment by Andarist** [comment] 2022-02-17 13:37
Sorry for that - we are aware of the issue and I plan to work on an opt-in flag that would address this. Changing the default behavior in v4 seems to be too risky, but this will become the default in v5. The problem is quite broad and perhaps I could group the involved scenarios and consider changing the default behavior for some of them - I'm not yet sure about it though, so no promises.

**Comment by rlaffers** [comment] 2022-02-17 14:49
Ah, I'm glad that you are aware of this. I struck upon this while playing with action creators to try to understand differences between `send` and `raise`. Not a big deal for me personally but I thought to report this because I wasn't sure if the semantics of `raise` actually justify such a behavior.

**Comment by davidkpiano** [comment] 2023-02-13 02:01
This is fixed in `xstate@alpha`

**Closed by davidkpiano** 2023-02-13 02:01 UTC
Labels: bug
