### ISSUE TITLE
Bug: Raise action causing typescript errors

### ISSUE THREAD

**Issue by xylophonehero** [statelyai/xstate#3846] opened 2023-02-20 10:22 UTC
### Description

When using a send expression in a `raise` action, we end up with a type error. Looks like `TEVENT` in the third generic of the `RaiseAction` isn't being inferred correctly

```
Type 'RaiseAction<unknown, { type: "ONE"; payload: string; }, { type: string; payload: number; }>' is not assignable to type 'ActionObject<unknown, { type: "ONE"; payload: string; }, { type: "ONE"; payload: string; } | { type: "TWO"; payload: number; } | { type: "xstate.init"; }, BaseActionObject> | ((context: unknown, event: { ...; }, meta: ActionMeta<...>) => void)'.
  Type 'RaiseAction<unknown, { type: "ONE"; payload: string; }, { type: string; payload: number; }>' is not assignable to type 'ActionObject<unknown, { type: "ONE"; payload: string; }, { type: "ONE"; payload: string; } | { type: "TWO"; payload: number; } | { type: "xstate.init"; }, BaseActionObject>'.
    Types of property 'exec' are incompatible.
      Type '(context: unknown, event: { type: "ONE"; payload: string; }, meta: ActionMeta<unknown, { type: string; payload: number; }, BaseActionObject>) => void' is not assignable to type '(context: unknown, event: { type: "ONE"; payload: string; }, meta: ActionMeta<unknown, { type: "ONE"; payload: string; } | { type: "TWO"; payload: number; } | { type: "xstate.init"; }, BaseActionObject>) => void'.
        Types of parameters 'meta' and 'meta' are incompatible.
          Type 'ActionMeta<unknown, { type: "ONE"; payload: string; } | { type: "TWO"; payload: number; } | { type: "xstate.init"; }, BaseActionObject>' is not assignable to type 'ActionMeta<unknown, { type: string; payload: number; }, BaseActionObject>'.
            Types of property '_event' are incompatible.
              Type 'Event<{ type: "ONE"; payload: string; } | { type: "TWO"; payload: number; } | { type: "xstate.init"; }>' is not assignable to type 'Event<{ type: string; payload: number; }>'.
                Type '{ type: "ONE"; payload: string; } | { type: "TWO"; payload: number; } | { type: "xstate.init"; }' is not assignable to type '{ type: string; payload: number; }'.
                  Type '{ type: "ONE"; payload: string; }' is not assignable to type '{ type: string; payload: number; }'.ts(2322)
```

See repo for events

### Expected result

Raise action with send expression should not make a TS error

### Actual result

Raise action makes a TS error when using a send expression

### Reproduction

https://codesandbox.io/s/hidden-dream-tog5jd?file=/src/machine.ts

### Additional context

This doesn't happen with static events with no send expression

**Comment by Andarist** [comment] 2023-02-20 13:18
I confirmed the issue - so far I didn't figure out a fix for this though. Gonna get to this in the coming days.

**Comment by Andarist** [comment] 2023-02-24 15:49
Wrapping `TEvent` within `SendExpr` with `NoInfer` [here](https://github.com/statelyai/xstate/blob/54ec3070dd4f8f8c454129b814290ff4ccb45498/packages/core/src/actions.ts#L168) helps with this **but** then the return value can't infer from it automatically - so you have to use things like `type: 'TWO' as const` to aid the checker.

Without `TEvent` within this `raise` gets inferred as `{ type: "TWO"; payload: number; }`. Perhaps it's a product of the union reduction there, TS trying to infer the narrowest possible thing. 

It's also all related to our `ActionMeta` argument - its presence messes up the assignability rules because `TEvent` invariant there or something like that. 

I will continue looking into this.

**Comment by Andarist** [comment] 2023-03-02 14:34
I start to believe that the correct solution is to:
1. Wrap `TEvent` with `NoInfer` within `SendExpr`. This would match what we already do for the other part of the union
2. Require users to put `as const` on the returned event type

I confirmed that those 2 fix the issue. The `as const` requirement is very unfortunate but I have already seen this issue in a couple of XState-less scenarios, it seems that perhaps it's the current TS limitation. I plan to dive into the compiler to understand why this happens and if there is anything we could do there to help with this - but for the time being I'm not sure how to avoid this `as const`.

**Comment by davidkpiano** [comment] 2023-04-13 22:24
The types work in `xstate@beta` - here is the code; it may not be apparent from CodeSandbox but if you pull down this project locally, you'll see the types as expected working there: https://codesandbox.io/s/busy-darkness-bsb6ee?file=/src/machine.ts

**Closed by davidkpiano** 2023-04-13 22:24 UTC
Labels: bug, typescript

**Comment by andrejpavlovic** [comment] 2023-10-17 04:01
I was still having an issue with inferring types from `raise` actions in `xstate@4.38.2`. What worked for me was to use a `pure` function instead which returns a single `raise` item.

e.g.

```typescript
'raise(SOME_EVENT)': pure((context) => {
  return [
    raise({
      type: 'SOME_EVENT',
      data: context.someValue,
    }),
  ]
}),
```
