### ISSUE TITLE
Type error returned from useActor

### ISSUE THREAD

**Issue by yaffol** [statelyai/xstate#2727] opened 2021-10-11 13:27 UTC
**Description**

A type error is returned when attempting to send a message to an actor which has been subscribed to use `useActor(actor)`

Whether the message is just a string, or an object (defined in the Event type of the target machine), a type error is thrown  `Type 'string' is not assignable to type 'never`.

**Expected Result**

The call to send(..) should not throw a type check error.
**Actual Result**

A type checking error is returned  `Type 'string' is not assignable to type 'never`.
**Reproduction**

https://codesandbox.io/s/provide-inject-actors-w-xstate-vue-forked-vg7qh?file=/src/toggle.machine.ts

**Additional context**

This occurs in both projects using vue3 and vue2 + composition api.

**Comment by davidkpiano** [comment] 2021-12-30 16:58
I cannot see the specific error in the CodeSandbox reproduction. Was the sandbox changed?

I'll reopen this if there is a valid repro.

**Comment by yaffol** [comment] 2022-01-27 10:46
Apologies, the link to the sandbox was incorrect.

This is the correct codesandbox https://codesandbox.io/s/ibyxc

If the sandbox container has already built and is running cached then you need to create a new terminal and `npm run build` to trigger the error.

**Comment by Andarist** [comment] 2022-01-27 15:16
I'm looking into this but so far I only see TS trying to troll me:
[TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOE7KMdGCgQWRmgCU0AzOAXzg6ggg4AcgAeAZxhY0wgFCyYATzBo4AFQgBzTQBs0AUQBuaYvAC8iOEpUAuEWoDyAcScAZfcJ7zkEYpLhCFqiY2HiEJGgAPEg+AK6mdsSxIABGaFA8FBraekYmMAB8ABQI3ACUsj5+8OJwFlTptGgwRSAVsgAmaMg6GOhWyqp5pg4cTCxQ7ByRauPQcGii2MQdtXOTnJEYxIoU24oFBXXq6wtLJqtw61ORJBzp6sP0cPtHAPyPxqZwiWjGUABuTrdXr9axDEDAGDYDqja6bWbMeaLZaXeHTfZ7HaHY6IiZnVFrJEbDE7Ch3B5qfSQ6FoDrvR40mE-OCkf5AhSDdRoSQARmOTzhxJu4IgXHEBVkcGlcAA9LK4AA9N6clTcyQAJgFTLpQomIsGYrgEqlMvlSpV4PVMAAzMdReKCRcifrNpiXti4B9+XYAAym6Xm5Wq1RqHkwAAs9sNjpRzquws2FIy+ixBy9cH0LP9MrlCuVQA)

**Comment by Andarist** [comment] 2022-03-03 08:38
Ok, I got to the bottom of this. This was a problem in the used `EventOfActorRef` helper type.

While `Interpreter` implements `ActorRef`:
https://github.com/statelyai/xstate/blob/3706c62f49daa5cf84172713a004eb26704342f5/packages/core/src/interpreter.ts#L116-L127
it does it in a way that turns out to be incompatible for this conditional type. The problem is demonstrated in this [TS playground](https://www.typescriptlang.org/play?ts=4.5.5#code/JYOwLgpgTgZghgYwgAgIILAeygJQjAHgBUBRANwnGQgA9IQATAZ2QG9kwBPABwgC5kTMFFABzZAF8AfGwBQyQZQYCAFBArgBpDWACUyALwyymYAwDcsibNkMICADZwoKR3CYsAkuGjcXkKGJySjBqOiUWdi5eASEREHFpeWRgAFtuBwhUkJZ0LFx8IJ0ZVmSmJVV1EK1g8ABtACJoiAaAXWQAH2RtEP0jZBMzS2tbeycXZARMECFBAW8AvwgAgiiefmQGgDEAeR2GySlLWVpubFDm7oghAEZDDnXMGEEw+mY0DGw8QjgQThkAPzIO4CAAMlgA9BCFDDYcgAHpAm4nGhnKAXdZXIQAJnuzSeL1ob1ynwKhFAMGgyBIgOpyAEICqUEh0LhsMRyEZFCgsiAA) - Interpreter's `send` accepts **more** than just `TEvent` and because of that the `infer TEvent` in the conditional type fails to extract the correct `TEvent`. 

Our own `EventFrom` helper works for `Interpreter`s cause they are special-cased within it. We'd suffer from the same issue if we would just rely on `ActorRef` matching in this type.
https://github.com/statelyai/xstate/blob/3706c62f49daa5cf84172713a004eb26704342f5/packages/core/src/types.ts#L1800-L1806

The issue [only~ happens in `xstate-vue2@0.1.1`](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOE7KMdeAXzgDMoIQ4ByADwGcYs0HOAHphcGAE8waHgC44AFgB0AJgAcSgAwAoUJFiI4AVx5oAgshjQ4jFm069+2ALQA3I2hVDR4qTPmaSgCMwdraktJwACoQAOaxADZoAKKuaMTwALyGEWjyHFEA8gDixQAyyUL0YcgQxHxw7NmomNh4hCRoADxItUYZ8sRGIABGaFA2FDHxSanpMAB8ABQI9ACU2rX18Dxw2VTjtGgwSyAbm3UNSKbEACY2e8amFlZQSzznN7crvtL5RaUKlUNkA) though as it got fixed in [this commit](https://github.com/ChrisShank/xstate-vue2/commit/02a115098dcf0d3366e65922e687400cd9f1b46b) and [the fix is available in `xstate-vue2@0.2.0`](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQWQ8gC2ADs0AaOE7KMdeAXzgDMoIQ4ByADwGcYs0HOAHphcGAE8waHgC44AFgB0AJgAcSgAwAoUJFiI4AVx5oAgshjQ4jFm069+2ALQA3I2hVDR4qTPmaqlra2pLScAAqEADm0QA2aACirmjE8AC8hmFo8hwRAPIA4oUAMolC9CHIEMR8cOyZqJjYeIQkaAA8SNVGafLERiAARmhQNhRRsQnJqTAAfAAUCPQAlNrVtfA8cJlUo7RoMAsga+s1dUimxAAmNjvGphZWUAs8p1fXS77SuQXFZRU1kA)

**Closed by Andarist** 2022-03-03 08:38 UTC
Labels: typescript, can't reproduce, 💚 @xstate/vue
