### ISSUE TITLE
Bug: invoke, onDone type incompatibility when `exactOptionalPropertyTypes: true`

### ISSUE THREAD

**Issue by pauldesmondparker** [statelyai/xstate#5119] opened 2024-11-07 09:00 UTC
### XState version

XState version 5

### Description

Reproduction on [typescritplang.org](https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true&ts=5.6.3#code/JYWwDg9gTgLgBAbzgQwM6uAcwHYBo4BmUEIACsSMKgKb40wCuYcAvoRXAOQAeqMyMapwDccOAHpxcGAE8w1VAC44AVgB0ARgAcagEwAoQ8GyCoBZAGNqcAKo0oifWOAATZdgYgARtSjCncNjIINTKfFDGmP4shtTckLBwFhDYfHAglgAWxtYAvHD0TAAUCAGy8kqOYmLJJnEwyghsaFXVYgz2AJJugZ4+fgFtHb4A-Mp2vv5tLLgBMwGWMNCVpW0E1DAWmRNQykQk5CRU1AA8O-hIw1Dd7n2+rAB8RWgy2BZwJXDGYAzwLACUcFyD1abVqaSgCkgqTyKAA7shgPBDpQaGpIagIAAbABu1BKgzaXx631+aiu3VmROqQRCyk4AAkGJgIJwqUSAVMiZDGFBsHAMdCaFyxAD2fMAWoLJCBNQALJZHIEsSSOBqdUBWqCbgNUFwCk9AAsunF7OMSOAyCx9NcWKE7L4spWhNtoT1YhSjUJbWoLiROwAIhtEViVtJkFBMBt6ViIMg-dhMDtOKx2dM06nCbH45Edl7qcYcRAANZu1bUgpQCz09abbb2Nne6qk3WfLX1ViA4EfcsV-VdHrtnXkgf4VUAFTk1mo2AI0CsLmkEDgPgKMAiiabov+GbaKQDKTLW+qi2AKUqaAwOGVfeqV2Un2oeJMnaBIKfM5gaggvx+MDHUgAMrrikmBYjI0hTouLQ7Me267tU8zUkhiGmvonJAA).

typescript: v5.6.3
xstate: 5.18.2

Code is the same as the #[invoke-and-typescript](https://stately.ai/docs/invoke#invoke-and-typescript) example with a few tweaks.

Navigate to `TS Config` and set `exactOptionalPropertyTypes`.
![image](https://github.com/user-attachments/assets/18bba23b-dd05-416c-b4c3-09b676faa8ff)

The resulting error on `onDone` will be:
> [!CAUTION]
> ```error
>           The types of '_out_TActor.src' are incompatible between these types.
>             Type 'string' is not assignable to type '"fetchUser"'. [2322]
>```

> [!Note]
> This only happens when I'm trying to use `assign`, otherwise no error.
> * (Probably anything in `actions` will set it off, but I didn't test that).

### Expected result

No typescript error.

### Actual result

```
   typescript: Type '{ actions: ActionFunction<{ userId: number; user?: User; }, DoneActorEvent<User, string>, AnyEventObject, undefined, ProvidedActor, never, never, never, never>; }' is not assignable to type 'SingleOrArray<TransitionConfigOrTarget<{ userId: number; user?: User; }, DoneActorEvent<User, string>, AnyEventObject, { src: "fetchUser"; logic: PromiseActorLogic<User, { userId: number; }, EventObject>; id: string | undefined; }, ... 4 more ..., MetaObject>>'.
     Types of property 'actions' are incompatible.
       Type 'ActionFunction<{ userId: number; user?: User; }, DoneActorEvent<User, string>, AnyEventObject, undefined, ProvidedActor, never, never, never, never>' is not assignable to type 'Actions<{ userId: number; user?: User; }, DoneActorEvent<User, string>, AnyEventObject, undefined, { src: "fetchUser"; logic: PromiseActorLogic<User, { ...; }, EventObject>; id: string | undefined; }, never, never, never, EventObject> | undefined'.
         Type 'ActionFunction<{ userId: number; user?: User; }, DoneActorEvent<User, string>, AnyEventObject, undefined, ProvidedActor, never, never, never, never>' is not assignable to type 'ActionFunction<{ userId: number; user?: User; }, DoneActorEvent<User, string>, AnyEventObject, undefined, { src: "fetchUser"; logic: PromiseActorLogic<User, { ...; }, EventObject>; id: string | undefined; }, never, never, never, EventObject>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
           The types of '_out_TActor.src' are incompatible between these types.
             Type 'string' is not assignable to type '"fetchUser"'. [2322]
```

### Reproduction

https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true&ts=5.6.3#code/JYWwDg9gTgLgBAbzgQwM6uAcwHYBo4BmUEIACsSMKgKb40wCuYcAvoRXAOQAeqMyMapwDccOAHpxcGAE8w1VAC44AVgB0ARgAcagEwAoQ8GyCoBZAGNqcAKo0oifWOAATZdgYgARtSjCncNjIINTKfFDGmP4shtTckLBwFhDYfHAglgAWxtYAvHD0TAAUCAGy8kqOYmLJJnEwyghsaFXVYgz2AJJugZ4+fgFtHb4A-Mp2vv5tLLgBMwGWMNCVpW0E1DAWmRNQykQk5CRU1AA8O-hIw1Dd7n2+rAB8RWgy2BZwJXDGYAzwLACUcFyD1abVqaSgCkgqTyKAA7shgPBDpQaGpIagIAAbABu1BKgzaXx631+aiu3VmROqQRCyk4AAkGJgIJwqUSAVMiZDGFBsHAMdCaFyxAD2fMAWoLJCBNQALJZHIEsSSOBqdUBWqCbgNUFwCk9AAsunF7OMSOAyCx9NcWKE7L4spWhNtoT1YhSjUJbWoLiROwAIhtEViVtJkFBMBt6ViIMg-dhMDtOKx2dM06nCbH45Edl7qcYcRAANZu1bUgpQCz09abbb2Nne6qk3WfLX1ViA4EfcsV-VdHrtnXkgf4VUAFTk1mo2AI0CsLmkEDgPgKMAiiabov+GbaKQDKTLW+qi2AKUqaAwOGVfeqV2Un2oeJMnaBIKfM5gaggvx+MDHUgAMrrikmBYjI0hTouLQ7Me267tU8zUkhiGmvonJAA

**Comment by pauldesmondparker** [comment] 2024-11-07 09:37
Short term remediation:
```ts
// @ts-expect-error exactOptionalPropertyTypes
```

**Comment by pauldesmondparker** [comment] 2024-11-20 03:46
Second remediation:
```ts
        onDone: {
          actions: ({ event }) => assign({
            user: event.output, // Strongly typed as User
          }),
        },
```
Making actions an anonymous function, either returning a single action or an array of actions works fine.

**Comment by dominicenglish** [comment] 2024-12-06 03:20
I have the same issue. I tried using `enqueueActions` to avoid using `assign` but it gives the exact same error. Seems like an issue with the built-in actions.

[Function assigners](https://stately.ai/docs/actions#with-function-assigners) gives the same error as well.

@pauldesmondparker I'm fairly sure your second remediation won't do anything (at least I can't make it do anything). I don't think you can provide a function that returns an action object.

`// @ts-expect-error exactOptionalPropertyTypes` is the only thing I've found that works.

**Comment by dominicenglish** [comment] 2024-12-06 03:35
Looks like this might be a duplicate of https://github.com/statelyai/xstate/issues/4613

**Comment by pauldesmondparker** [comment] 2024-12-06 03:38
You're right. The second remediation was completely useless. For arrays it removed the error, but was non-functional (i.e. despite satisfying typescript, it just doesn't work).

**Closed** 2024-12-06 03:38 UTC
Labels: bug
