### ISSUE TITLE
External self-transition does not work as expected inside parallel state

### ISSUE THREAD

**Issue by korrix** [statelyai/xstate#2401] opened 2021-07-09 08:09 UTC
**Description**
External self-transition does not invoke entry/exit actions if the state is member of a parallel state

**Expected Result**
State should get exitted and reentered

**Actual Result**
Nothing happens

**Reproduction**
- [CodeSandbox](https://codesandbox.io/s/young-shadow-2jboh?file=/src/index.ts)

**Additional context**
XState 4.22.0

**Comment by Andarist** [comment] 2023-11-10 15:08
This repro case doesn't contain any external transitions so I'm not sure how to properly interpret it. You also mentioned the "actual result" as "nothing happens" but one of the states here is actually exited but not reentered and that's definitely a bug in v4. I created a PR that targets v5 branch with extra tests based on this repro and I can confirm that the behavior there is correct: https://github.com/statelyai/xstate/pull/4450

I'll close this issue since it's hard to tell what it is about after all of this time. We are sorry that this has slipped through the cracks and that we didn't get to it sooner. If you manage to take a look at this and file a new issue with more details - I'd certainly appreciate it.

**Closed by Andarist** 2023-11-10 15:08 UTC
Labels: core, XState v5 essential
