### ISSUE TITLE
Bug: 'spawn(machine)' does not validate missing actions like 'useMachine(machine)' does

### ISSUE THREAD

**Issue by kirill578** [statelyai/xstate#3725] opened 2022-12-23 19:20 UTC
### Description

it appears that machines that are spawned lack the validation we get with useMachine. Looks like the spawn action is accepting machines that have a non 'never' values under `tsConfig.missingImplementations`

![Screen Shot 2022-12-23 at 10 51 36 AM](https://user-images.githubusercontent.com/2484508/209395837-3d715b18-b561-463a-b216-6b09487f8319.png)

### Expected result

it should throw a typescript error when invoking a non fully implemented machine

### Actual result

it does not error

### Reproduction

https://codesandbox.io/s/elastic-visvesvaraya-lgbnlj?file=/src/index.ts

**Comment by kirill578** [comment] 2023-01-11 17:24
I ended up adding this no-op wrapper workaround to my machines to ensure they are fully defined:

```ts
import {
  AnyStateMachine,
  AreAllImplementationsAssumedToBeProvided,
} from "xstate";

// workaround for this bug https://github.com/statelyai/xstate/issues/3725
export function confirmAllImplementationsAreProvided<
  TMachine extends AnyStateMachine
>(
  m: AreAllImplementationsAssumedToBeProvided<
    TMachine["__TResolvedTypesMeta"]
  > extends true
    ? TMachine
    : never
): TMachine {
  return m;
}

````


```ts
spawn(AreAllImplementationsAssumedToBeProvided(myMachine))
```

**Comment by Andarist** [comment] 2023-09-14 11:48
Duplicate of https://github.com/statelyai/xstate/issues/3405

**Closed by Andarist** 2023-09-14 11:48 UTC
Labels: bug, has workaround
